services:
  postgres:
    container_name: postgres-sql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bash
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopify-db
    networks:
      - shopify-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  shopify:
    container_name: shopify
    image: shopify
    ports:
      - "8080:8080"
    networks:
      - shopify-postgres
    depends_on:
      - postgres
volumes:
  postgres:

networks:
  shopify-postgres:
    driver: bridge

