version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: shopify-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shopify
    ports:
      - "5432:5432"
    networks:
      - shopify-network
    volumes:
      - postgres-data:/var/lib/postgresql/data


  backend:
    build: .
    container_name: shopify-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - shopify-network

networks:
  shopify-network:
    driver: bridge

