services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopify-db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data/
    networks:
      - spring-postgres
  spring-boot:
    container_name: spring-backend
    image: shopify-backend
    ports:
      - "8080:8080"
    networks:
      - spring-postgres

volumes:
  postgres:

networks:
  spring-postgres:
    driver: bridge
